# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Fei's Notes
tagline:          a personal log   
url:              http://feizhu.github.io/notes/
paginate:         1
baseurl:          /notes
author:
  name:           Fei Zhu
  url:            http://feizhu.github.io/
  email:

# For MathJax          
markdown: kramdown
kramdown:
  input: GFM
