# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Fei's Blog
tagline:       a personal log   
url:              http://feizhu.github.io/blog/
paginate:         1
baseurl:          /blog
author:
  name:           Fei Zhu
  url:            http://feizhu.github.io/
  email:

# For MathJax          
markdown: maruku
