# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Fei's Blog
tagline:          
url:              http://feizhu.github.io/blog/
paginate:         1
baseurl:          /blog
author:
  name:           Fei Zhu
  url:            http://feizhu.github.io/
  email:          

# Custom vars
version:          1.0.0
github:
  repo:           
